# Generated by Django 5.0.6 on 2024-07-06 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prep_time', models.DurationField(default=datetime.timedelta(seconds=600))),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('vegetarian', models.BooleanField()),
                ('recipe_img', models.ImageField(upload_to='recipe')),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
    ]
