# Generated by Django 5.0.6 on 2024-07-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipe', '0002_alter_recipes_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='vegetarian',
            field=models.CharField(blank=True, choices=[('Non Veg', 'Non Veg'), ('Veg', 'Veg'), ('Both', 'Both')], max_length=15),
        ),
    ]
