# Generated by Django 5.0.6 on 2024-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipe', '0003_alter_recipes_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=15),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='vegetarian',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non.Veg', 'Non.Veg'), ('Both', 'Both')], max_length=15),
        ),
    ]
