# Generated by Django 5.0.6 on 2024-07-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Receipe', '0004_alter_recipes_difficulty_alter_recipes_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='difficulty',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='prep_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='vegetarian',
            field=models.CharField(max_length=10),
        ),
    ]
