# Generated by Django 5.0.6 on 2024-07-27 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Receipe', '0005_alter_recipes_difficulty_alter_recipes_prep_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='difficulty',
        ),
    ]
